// frontend/src/pages/admin/caseForm.jsx
import {
    Accordion,
    Alert,
    Button,
    Container,
    Group,
    NumberInput,
    Paper,
    Stack,
    Text,
    Textarea,
    TextInput,
    Title,
} from '@mantine/core'
import { useQuery } from '@tanstack/react-query'
import { produce } from 'immer'
import { useCallback, useEffect, useRef, useState } from 'react'
import { apiFetch } from '../../client.js'
import { useCaseSubmit } from '../../hooks/useCaseSubmit.js'
import { buildHTMLDoc, downloadForm } from './exportCase.js'
import {
    collectReferredPersonas,
    createEmptyPersona,
    getPersonaFieldErrors,
    getPersonaLabel,
    hasFieldErrors,
    normalizePersona,
    normalizeReferral,
} from './Helpers.js'
import { CaseImportError, parseCaseHtmlDocument } from './importCase.js'
import PersonaFields from './PersonaFields.jsx'

const MAX_SIMULATION_DURATION = 120

function CaseForm({ templateId, editCaseId }) {
    const [caseName, setCaseName] = useState('')
    const [initialBrief, setInitialBrief] = useState('')
    const [commonInformation, setCommonInformation] = useState('')
    const [simulationDurationMinutes, setSimulationDurationMinutes] = useState(null)
    const [accessCode, setAccessCode] = useState('')
    const [totalPersonas, setTotalPersonas] = useState(null)
    const [personas, setPersonas] = useState([])
    const isEditMode = Boolean(editCaseId)
    const showPersonas = typeof totalPersonas === 'number' && totalPersonas >= 1
    const sourceCaseId = editCaseId || templateId

    // Import is only offered on the blank "from scratch" new-case route
    const canImport = !sourceCaseId

    const [showFieldErrors, setShowFieldErrors] = useState(false)
    const revealErrors = useCallback(() => setShowFieldErrors(true), [])
    const [importWarnings, setImportWarnings] = useState([])
    const [importError, setImportError] = useState('')
    const fileInputRef = useRef(null)

    // `recipe` mutates an Immer draft of the target persona; Immer produces the new immutable state.
    // The target is normalized first so recipes can freely touch its files/referrals arrays.
    const updatePersonaAt = useCallback(
        (index, recipe) => {
            revealErrors()
            setPersonas(
                produce((draft) => {
                    draft[index] = normalizePersona(draft[index])
                    recipe(draft[index])
                }),
            )
        },
        [revealErrors],
    )

    // path — walk down the referral tree to the referred persona.
    const updateReferredPersona = useCallback(
        (path, recipe) => {
            revealErrors()
            setPersonas(
                produce((draft) => {
                    draft[path[0]] = normalizePersona(draft[path[0]])
                    let persona = draft[path[0]]
                    for (let depth = 1; depth < path.length; depth++) {
                        const referralIndex = path[depth]
                        persona.referrals[referralIndex] = normalizeReferral(persona.referrals[referralIndex])
                        persona = persona.referrals[referralIndex].persona
                    }
                    recipe(persona)
                }),
            )
        },
        [revealErrors],
    )

    const caseNameError = !caseName.trim() ? 'Case name is required.' : null
    const initialBriefError = !initialBrief.trim() ? 'Initial brief is required.' : null
    const accessCodeError = !accessCode.trim() ? 'Access code is required.' : null

    const totalPersonasError =
        typeof totalPersonas !== 'number' || totalPersonas < 1
            ? 'At least 1 persona is required'
            : null

    const simulationDurationError =
        typeof simulationDurationMinutes === 'number' &&
        (simulationDurationMinutes > MAX_SIMULATION_DURATION ||
            simulationDurationMinutes < 1)
            ? `Simulation duration must be between 1 and ${MAX_SIMULATION_DURATION} minutes (2 hours).`
            : null

    const {
        data: loadedCase,
        isFetching: isLoadingTemplate,
        error: loadError,
    } = useQuery({
        queryKey: ['case', sourceCaseId],
        queryFn: () => apiFetch(`/api/cases/${sourceCaseId}`),
        enabled: Boolean(sourceCaseId),
    })

    const { submitError, submitSuccess, submitCase } = useCaseSubmit({
        isEditMode, editCaseId
    })

    const [loadErrorMessage, setLoadErrorMessage] = useState('')

    useEffect(() => {
        if (!loadedCase?.case) return
        const templateCase = loadedCase.case
        setCaseName(templateCase.case_name ?? '')
        setInitialBrief(templateCase.initial_brief ?? '')
        setCommonInformation(templateCase.common_information ?? '')
        setSimulationDurationMinutes(templateCase.simulation_duration ?? null)
        setAccessCode(templateCase.access_code ?? '')
        setTotalPersonas(templateCase.total_non_referred_personas ?? null)
        setPersonas((templateCase.personas ?? []).map((persona) => normalizePersona(persona)))
        revealErrors()
    }, [loadedCase, revealErrors])

    useEffect(() => {
        if (loadError) {
            setLoadErrorMessage(
                loadError.message ||
                    (isEditMode ? 'Failed to load case for editing.' : 'Failed to load case template.'))
        }
    }, [loadError, isEditMode])

    const handleSubmit = (event) => {
        event.preventDefault()
        setLoadErrorMessage('')
        submitCase({
            caseName,
            initialBrief,
            commonInformation,
            simulationDurationMinutes,
            accessCode,
            totalPersonas,
            personas,
        })
    }

    // Builds a .html form from whatever's currently in this form
    const handleExportTemplate = () => {
        const html = buildHTMLDoc({
            caseName,
            accessCode,
            simulationDurationMinutes,
            initialBrief,
            commonInformation,
            personas,
        })
        downloadForm(html, caseName)
    }

    const handleImportClick = () => fileInputRef.current?.click()

    // Parses a filled-in export back into form state
    const handleImportFile = async (event) => {
        const file = event.target.files?.[0]
        event.target.value = ''
        if (!file) return

        const hasExistingData =
            caseName.trim() || initialBrief.trim() || accessCode.trim() || personas.length > 0
        if (hasExistingData && !window.confirm('Import will replace everything currently in this form. Continue?')) {
            return
        }

        setImportError('')
        setImportWarnings([])
        try {
            const text = await file.text()
            const { data, warnings } = parseCaseHtmlDocument(text)
            setCaseName(data.caseName)
            setAccessCode(data.accessCode)
            setInitialBrief(data.initialBrief)
            setCommonInformation(data.commonInformation)
            setSimulationDurationMinutes(data.simulationDurationMinutes)
            setTotalPersonas(data.totalPersonas)
            setPersonas(data.personas)
            setImportWarnings(warnings)
            revealErrors()
        } catch (error) {
            setImportError(
                error instanceof CaseImportError
                    ? error.message
                    : 'Failed to read that file. Make sure it’s an unmodified export from this app.',
            )
        }
    }

    const referredPersonas = collectReferredPersonas(personas)
    const displayedError = submitError || loadErrorMessage

    const rootPersonaErrors = Array.from({ length: showPersonas ? totalPersonas : 0 }, (_, index) =>
        getPersonaFieldErrors(normalizePersona(personas[index])),
    )
    const referredPersonaErrors = referredPersonas.map((item) => getPersonaFieldErrors(item.persona))
    const hasAnyPersonaError =
        rootPersonaErrors.some(hasFieldErrors) || referredPersonaErrors.some(hasFieldErrors)
    const hasValidationErrors =
        Boolean(caseNameError) ||
        Boolean(initialBriefError) ||
        Boolean(accessCodeError) ||
        Boolean(totalPersonasError) ||
        Boolean(simulationDurationError) ||
        hasAnyPersonaError

    return (
        <div className="relative min-h-screen bg-parchment">
            <div className="absolute inset-x-0 top-0 h-1 bg-brand" aria-hidden="true" />
            <Container size="2xl" py="xl">
                <Paper radius="lg" p="xl" withBorder shadow="sm" style={{ borderColor: '#e4dfd5' }}>
                    <form onSubmit={handleSubmit}>
                        <Stack gap="lg">
                            <div className="relative">
                                <div className="text-center">
                                    <p className="font-mono text-[11px] font-medium uppercase tracking-[0.28em] text-brand">
                                        Case Builder
                                    </p>
                                    <Title order={1} ta="center" mt={6}>
                                        {isEditMode ? 'Edit Case Study' : 'New Case Study'}
                                    </Title>
                                </div>
                                <div className="absolute right-0 top-0">
                                    <Group gap="xs">
                                        {canImport && (
                                            <>
                                                <input
                                                    ref={fileInputRef}
                                                    type="file"
                                                    accept=".html,.htm,text/html"
                                                    className="hidden"
                                                    onChange={handleImportFile}
                                                />
                                                <Button
                                                    type="button"
                                                    variant="outline"
                                                    size="xs"
                                                    onClick={handleImportClick}
                                                >
                                                    Import template
                                                </Button>
                                            </>
                                        )}
                                        <Button
                                            type="button"
                                            variant="outline"
                                            size="xs"
                                            onClick={handleExportTemplate}
                                        >
                                            Export template
                                        </Button>
                                    </Group>
                                </div>
                            </div>
                        {isLoadingTemplate && (
                            <Text c="dimmed" size="sm" ta="center">
                                {isEditMode ? 'Loading case...' : 'Loading case template...'}
                            </Text>
                        )}
                        {importError && (
                            <Alert color="red" variant="light" withCloseButton onClose={() => setImportError('')}>
                                {importError}
                            </Alert>
                        )}
                        {importWarnings.length > 0 && (
                            <Alert
                                color="yellow"
                                variant="light"
                                title={`Imported with ${importWarnings.length} issue${importWarnings.length === 1 ? '' : 's'} to review`}
                                withCloseButton
                                onClose={() => setImportWarnings([])}
                            >
                                <Stack gap={4}>
                                    {importWarnings.map((warning) => (
                                        <Text key={warning} size="sm">
                                            {warning}
                                        </Text>
                                    ))}
                                </Stack>
                            </Alert>
                        )}

                        <Accordion defaultValue="case-info" variant="separated">
                            {/*Section 1*/}
                            <Accordion.Item value="case-info">
                                <Accordion.Control fw={700} fz="lg">
                                    Case Information
                                </Accordion.Control>
                                <Accordion.Panel>
                                    <Stack gap="md">
                                        <TextInput
                                            label="Case name"
                                            placeholder="Enter case name"
                                            required
                                            value={caseName}
                                            error={showFieldErrors ? caseNameError : null}
                                            onChange={(event) => {
                                                revealErrors()
                                                setCaseName(event.currentTarget.value)
                                            }}
                                        />
                                        <Textarea
                                            label="Initial brief"
                                            placeholder="Summarize the initial brief"
                                            minRows={3}
                                            autosize
                                            required
                                            value={initialBrief}
                                            error={showFieldErrors ? initialBriefError : null}
                                            onChange={(event) => {
                                                revealErrors()
                                                setInitialBrief(event.currentTarget.value)
                                            }}
                                        />
                                        <Textarea
                                            label="Enter Case Background"
                                            placeholder="Describe the common information"
                                            minRows={3}
                                            autosize
                                            value={commonInformation}
                                            onChange={(event) => {
                                                setCommonInformation(event.currentTarget.value)
                                            }}
                                        />
                                        <NumberInput
                                            label="Simulation duration (Minutes)"
                                            placeholder="Leave empty for unlimited"
                                            min={1}
                                            max={MAX_SIMULATION_DURATION}
                                            allowDecimal={false}
                                            hideControls
                                            value={simulationDurationMinutes}
                                            error={simulationDurationError}
                                            onChange={(value) => {
                                                revealErrors()
                                                setSimulationDurationMinutes(value)
                                            }}
                                        />
                                        <TextInput
                                            label="Access code"
                                            placeholder="Enter access code"
                                            required
                                            value={accessCode}
                                            error={showFieldErrors ? accessCodeError : null}
                                            onChange={(event) => {
                                                revealErrors()
                                                setAccessCode(event.currentTarget.value)
                                            }}
                                        />
                                        <NumberInput
                                            label="Enter the Number of AI personas that are not referred"
                                            placeholder="e.g., 5"
                                            min={1}
                                            allowDecimal={false}
                                            required
                                            hideControls
                                            value={totalPersonas}
                                            error={showFieldErrors ? totalPersonasError : null}
                                            onChange={(value) => {
                                                revealErrors()
                                                setTotalPersonas(value)
                                                if (typeof value === 'number' && value >= 1) {
                                                    setPersonas((prev) => {
                                                        const next = [...prev]
                                                        if (next.length > value) {
                                                            return next.slice(0, value)
                                                        }
                                                        while (next.length < value) {
                                                            next.push(createEmptyPersona())
                                                        }
                                                        return next
                                                    })
                                                } else {
                                                    setPersonas([])
                                                }
                                            }}
                                        />
                                    </Stack>
                                </Accordion.Panel>
                            </Accordion.Item>
                            <Accordion.Item value="ai-personas">
                                <Accordion.Control fw={700} fz="lg">
                                    AI Personas
                                </Accordion.Control>
                                <Accordion.Panel>
                                    {showPersonas && (
                                        <Accordion variant="separated">
                                            {Array.from({ length: totalPersonas }, (_, index) => {
                                                const personaNumber = index + 1
                                                const persona = normalizePersona(personas[index])
                                                const personaLabel = getPersonaLabel(
                                                    persona,
                                                    `Persona ${personaNumber}`,
                                                )
                                                return (
                                                    <Accordion.Item
                                                        key={`persona-${personaNumber}`}
                                                        value={`persona-${personaNumber}`}
                                                    >
                                                        <Accordion.Control>
                                                            {personaLabel}
                                                        </Accordion.Control>
                                                        <Accordion.Panel>
                                                            <PersonaFields
                                                                persona={persona}
                                                                updatePersona={(recipe) =>
                                                                    updatePersonaAt(index, recipe)
                                                                }
                                                                errors={
                                                                    showFieldErrors
                                                                        ? rootPersonaErrors[index]
                                                                        : {}
                                                                }
                                                            />
                                                        </Accordion.Panel>
                                                    </Accordion.Item>
                                                )
                                            })}
                                            {referredPersonas.map((item, referredIndex) => {
                                                const pathKey = item.path.join('-')
                                                return (
                                                    <Accordion.Item
                                                        key={`referred-${pathKey}`}
                                                        value={`referred-${pathKey}`}
                                                    >
                                                        <Accordion.Control>
                                                            {`${item.label} <- ${item.parentLabel}`}
                                                        </Accordion.Control>
                                                        <Accordion.Panel>
                                                            <PersonaFields
                                                                persona={item.persona}
                                                                updatePersona={(recipe) =>
                                                                    updateReferredPersona(
                                                                        item.path,
                                                                        recipe,
                                                                    )
                                                                }
                                                                errors={
                                                                    showFieldErrors
                                                                        ? referredPersonaErrors[
                                                                              referredIndex
                                                                          ]
                                                                        : {}
                                                                }
                                                            />
                                                        </Accordion.Panel>
                                                    </Accordion.Item>
                                                )
                                            })}
                                        </Accordion>
                                    )}
                                </Accordion.Panel>
                            </Accordion.Item>
                        </Accordion>
                        {displayedError && (
                            <Text c="red" size="sm">
                                {displayedError}
                            </Text>
                        )}
                        {submitSuccess && (
                            <Text c="green" size="sm">
                                {submitSuccess}
                            </Text>
                        )}
                        {showFieldErrors && hasValidationErrors && (
                            <Text c="red" size="sm">
                                Resolve the highlighted fields above before submitting.
                            </Text>
                        )}
                        <Button
                            type="submit"
                            disabled={isLoadingTemplate || hasValidationErrors}
                        >
                            Submit
                        </Button>
                    </Stack>
                </form>
            </Paper>
            </Container>
        </div>
    )
}

export default CaseForm

// src/lib/components/CaseForm.svelte
<script lang="ts">
import { getConvexClient, useQuery } from "convex-svelte";
import { onDestroy, onMount, untrack } from "svelte";
import { toast } from "svelte-sonner";
import { getViewerContext } from "#lib/adminViewer.js";
import {
	getCaseInfoErrors,
	hasFieldErrors,
	parseCaseStructure,
} from "#lib/case/draft.js";
import { buildHTMLForm, downloadForm } from "#lib/case/exportCase.js";
import { CaseGraph } from "#lib/case/graph.svelte.js";
import { CaseImportError, parseHTMLForm } from "#lib/case/importCase.js";
import { submitCase } from "#lib/case/submitCase.js";
import { getErrorMessage } from "#lib/errors.js";
import { type SaveResult, unsavedGuard } from "#lib/unsavedGuard.svelte.js";
import { beforeNavigate, goto } from "$app/navigation";
import { api } from "../../../convex/_generated/api.js";
import type { Id } from "../../../convex/_generated/dataModel.js";
import { RUN_LIFETIME_MINUTES } from "../../../convex/lib/constants.js";
import CaseGraphEditor from "./CaseGraphEditor.svelte";
import CaseInfoFields from "./CaseInfoFields.svelte";
import DestructiveConfirmDialog from "./DestructiveConfirmDialog.svelte";

const MAX_SIMULATION_DURATION = RUN_LIFETIME_MINUTES;

type Props = {
	mode: "create" | "edit";
	caseId?: string | null;
	templateId?: string | null;
};

let { mode, caseId = null, templateId = null }: Props = $props();

const isEditMode = $derived(mode === "edit");
const editCaseId = $derived(isEditMode ? caseId : null);
const sourceCaseId = $derived(editCaseId || templateId);
const canImport = $derived(!sourceCaseId);

let caseName = $state("");
let initialBrief = $state("");
let commonInformation = $state("");
let simulationDurationMinutes = $state<number | null>(null);
let accessCode = $state("");
const graph = new CaseGraph();

const adminsQuery = useQuery(api.api.admins.listAll, {});
const allAdmins = $derived(adminsQuery.data ?? []);
const viewerQuery = getViewerContext();
let collaboratorAdminIds = $state<string[]>([]);
let ownerAdminId = $state<string | null>(null);

let baselineScalars = $state<{
	caseName: string;
	initialBrief: string;
	commonInformation: string;
	simulationDurationMinutes: number | null;
	accessCode: string;
	collaboratorAdminIds: string[];
} | null>(null);
let baselineGraphSnapshot = $state<string | null>(null);

// Replaces File values with a small descriptor so the form can be snapshotted as JSON.
function jsonReplacer(_key: string, value: unknown): unknown {
	if (value instanceof File) {
		return {
			name: value.name,
			size: value.size,
			lastModified: value.lastModified,
		};
	}
	return value;
}

// Serializes the persona graph to a string for change detection.
function snapshotGraph(): string {
	return JSON.stringify(
		{
			personas: graph.personas,
			referrals: graph.referrals,
			roots: graph.roots,
		},
		jsonReplacer,
	);
}

// Records the current form values as the clean baseline for dirty tracking.
function markSaved(): void {
	baselineScalars = {
		caseName,
		initialBrief,
		commonInformation,
		simulationDurationMinutes,
		accessCode,
		collaboratorAdminIds: [...collaboratorAdminIds],
	};
	baselineGraphSnapshot = snapshotGraph();
}

// svelte-ignore state_referenced_locally
if (!sourceCaseId) markSaved();

const scalarsDirty = $derived.by(() => {
	const baseline = baselineScalars;
	if (baseline === null) return false;
	return (
		caseName !== baseline.caseName ||
		initialBrief !== baseline.initialBrief ||
		commonInformation !== baseline.commonInformation ||
		simulationDurationMinutes !== baseline.simulationDurationMinutes ||
		accessCode !== baseline.accessCode ||
		collaboratorAdminIds.length !== baseline.collaboratorAdminIds.length ||
		collaboratorAdminIds.some(
			(id, i) => id !== baseline.collaboratorAdminIds[i],
		)
	);
});
const graphDirty = $derived(
	baselineGraphSnapshot !== null && snapshotGraph() !== baselineGraphSnapshot,
);
const isDirty = $derived(scalarsDirty || graphDirty);

let showFieldErrors = $state(false);
// Turns on display of field validation errors.
function revealErrors() {
	showFieldErrors = true;
}

let isLoadingSource = $state(untrack(() => Boolean(sourceCaseId)));
let loadErrorMessage = $state("");
let submitError = $state("");
let submitSuccess = $state("");
let suppressInlineSuccess = $state(false);
let isSubmitting = $state(false);
let importWarnings = $state<string[]>([]);
let pendingImportFile = $state<File | null>(null);
let fileInputEl = $state<HTMLInputElement | null>(null);
let lastSavedCaseId: string | null = null;

// Loads a case (or template) from the server into the form and marks it clean.
async function loadCase(id: string): Promise<void> {
	const loadedCase = await getConvexClient().query(api.api.cases.getForEdit, {
		caseId: id as Id<"cases">,
	});
	if (sourceCaseId !== id) return;
	caseName = loadedCase.name ?? "";
	initialBrief = loadedCase.brief ?? "";
	commonInformation = loadedCase.commonInformation ?? "";
	simulationDurationMinutes = loadedCase.duration ?? null;
	accessCode = isEditMode ? loadedCase.accessCode : "";
	graph.load(parseCaseStructure(loadedCase.structure));
	if (isEditMode) {
		collaboratorAdminIds = loadedCase.collaboratorAdminIds ?? [];
		ownerAdminId = loadedCase.ownerAdminId ?? null;
	}
	revealErrors();
	markSaved();
}

$effect(() => {
	if (!sourceCaseId) return;
	const id = sourceCaseId;
	isLoadingSource = true;
	loadErrorMessage = "";
	loadCase(id)
		.catch((err: unknown) => {
			if (sourceCaseId !== id) return;
			loadErrorMessage = getErrorMessage(
				err,
				isEditMode
					? "Failed to load case for editing."
					: "Failed to load case template.",
			);
		})
		.finally(() => {
			if (sourceCaseId !== id) return;
			isLoadingSource = false;
		});
});

const effectiveOwnerId = $derived(
	isEditMode ? ownerAdminId : (viewerQuery.data?._id ?? null),
);

const caseInfoErrors = $derived(
	getCaseInfoErrors({
		caseName,
		initialBrief,
		accessCode,
		simulationDurationMinutes,
		maxSimulationDuration: MAX_SIMULATION_DURATION,
	}),
);
const caseInfoHasErrors = $derived(hasFieldErrors(caseInfoErrors));

const graphValidation = $derived(graph.validation);
const hasValidationErrors = $derived(
	caseInfoHasErrors || graphValidation.hasErrors,
);
const displayedError = $derived(submitError || loadErrorMessage);

// Exports the current form as a downloadable HTML template.
function handleExportTemplate(): void {
	const html = buildHTMLForm({
		caseName,
		accessCode,
		simulationDurationMinutes,
		initialBrief,
		commonInformation,
		personas: graph.personas,
		referrals: graph.referrals,
		roots: graph.roots,
	});
	downloadForm(html);
}

// Opens the file picker for importing an exported case.
function handleImportClick(): void {
	fileInputEl?.click();
}

// Handles a chosen import file, asking for confirmation first if the form already has content.
function handleImportFile(
	event: Event & { currentTarget: EventTarget & HTMLInputElement },
): void {
	const file = event.currentTarget.files?.[0];
	event.currentTarget.value = "";
	if (!file) return;

	const hasExistingData =
		caseName.trim() ||
		initialBrief.trim() ||
		accessCode.trim() ||
		graph.personas.length > 0;
	if (hasExistingData) {
		pendingImportFile = file;
		return;
	}
	void performImport(file);
}

// Imports the file the user confirmed replacing the form with.
async function confirmImport(): Promise<void> {
	const file = pendingImportFile;
	pendingImportFile = null;
	if (file) await performImport(file);
}

// Parses an exported HTML form into the form fields, or shows a toast if the file is unusable.
async function performImport(file: File): Promise<void> {
	importWarnings = [];
	try {
		const text = await file.text();
		const { data, warnings } = parseHTMLForm(text);
		caseName = data.caseName;
		accessCode = data.accessCode;
		initialBrief = data.initialBrief;
		commonInformation = data.commonInformation;
		simulationDurationMinutes = data.simulationDurationMinutes;
		graph.load({
			personas: data.personas,
			referrals: data.referrals,
			roots: data.roots,
		});
		importWarnings = warnings;
		revealErrors();
	} catch (err) {
		toast(
			err instanceof CaseImportError
				? err.message
				: "Failed to read that file. Make sure it’s an unmodified export from this app.",
		);
	}
}

let inFlightSave: Promise<SaveResult> | null = null;

// Saves the form, reusing the save already in flight if there is one.
function performSave(): Promise<SaveResult> {
	if (inFlightSave) return inFlightSave;
	const attempt = runSave();
	inFlightSave = attempt.finally(() => {
		inFlightSave = null;
	});
	return inFlightSave;
}

// Validates and submits the case, then updates the success, error and baseline state.
async function runSave(): Promise<SaveResult> {
	revealErrors();
	if (hasValidationErrors) {
		const message = "Resolve the highlighted fields before saving.";
		submitError = message;
		return { ok: false, error: message };
	}
	loadErrorMessage = "";
	submitError = "";
	submitSuccess = "";
	suppressInlineSuccess = false;
	isSubmitting = true;
	try {
		const result = await submitCase({
			editCaseId,
			caseName,
			initialBrief,
			commonInformation,
			simulationDurationMinutes,
			accessCode,
			personas: graph.personas,
			referrals: graph.referrals,
			roots: graph.roots,
			collaboratorAdminIds,
		});
		lastSavedCaseId = result.caseId;
		submitSuccess = isEditMode
			? "Case updated successfully."
			: "Case saved successfully.";
		if (isEditMode && editCaseId) {
			try {
				await loadCase(editCaseId);
			} catch {
				markSaved();
			}
		} else {
			markSaved();
		}
		return { ok: true };
	} catch (err) {
		const message = getErrorMessage(err, "Failed to save the case.");
		submitError = message;
		return { ok: false, error: message };
	} finally {
		isSubmitting = false;
	}
}

// Handles the form submit, moving to the new case's edit page after a first save.
async function handleSubmit(event: SubmitEvent): Promise<void> {
	event.preventDefault();
	const result = await performSave();
	if (result.ok && !isEditMode && lastSavedCaseId) {
		suppressInlineSuccess = true;
		toast(submitSuccess);
		await goto(`/admin/cases/${lastSavedCaseId}/edit`);
	}
}

beforeNavigate((navigation) => {
	if (!unsavedGuard.isDirty) return;
	const targetUrl = navigation.to?.url;
	if (!targetUrl) return;
	navigation.cancel();
	const resume =
		navigation.type === "popstate" && navigation.delta !== undefined
			? () => history.go(navigation.delta)
			: () => goto(targetUrl);
	unsavedGuard.requestNavigation(resume);
});

onMount(() => {
	unsavedGuard.register(() => isDirty, performSave);
	function handleBeforeUnload(event: BeforeUnloadEvent): void {
		if (!unsavedGuard.isDirty) return;
		event.preventDefault();
		event.returnValue = "";
	}
	window.addEventListener("beforeunload", handleBeforeUnload);
	return () => window.removeEventListener("beforeunload", handleBeforeUnload);
});

onDestroy(() => {
	unsavedGuard.unregister();
});
</script>

<div class="relative min-h-screen bg-parchment">
	<div class="absolute inset-x-0 top-0 h-1 bg-brand" aria-hidden="true"></div>
	<div class="mx-auto max-w-4xl px-6 py-10">
		<div class="rounded-2xl border border-line bg-white p-8 shadow-soft">
			<form novalidate onsubmit={handleSubmit} class="flex flex-col gap-6">
				<fieldset disabled={isSubmitting || isLoadingSource} class="contents">
				<div class="relative">
					<div class="text-center">
						<p class="font-mono text-[11px] font-medium uppercase tracking-[0.28em] text-brand">
							Case Builder
						</p>
						<h1 class="mt-1.5 font-display text-3xl font-semibold text-ink">
							{isEditMode ? 'Edit Case Study' : 'New Case Study'}
						</h1>
					</div>
					<div class="absolute right-0 top-0 flex gap-2">
						{#if canImport}
							<input
								bind:this={fileInputEl}
								type="file"
								accept=".html,.htm,text/html"
								class="hidden"
								onchange={handleImportFile}
							/>
							<button
								type="button"
								onclick={handleImportClick}
								class="rounded-lg border border-line px-3 py-1.5 text-xs font-semibold text-ink-soft transition hover:border-brand hover:text-brand disabled:cursor-not-allowed disabled:opacity-60"
							>
								Import template
							</button>
						{/if}
						<button
							type="button"
							onclick={handleExportTemplate}
							class="rounded-lg border border-line px-3 py-1.5 text-xs font-semibold text-ink-soft transition hover:border-brand hover:text-brand disabled:cursor-not-allowed disabled:opacity-60"
						>
							Export template
						</button>
					</div>
				</div>

				{#if isLoadingSource}
					<p class="text-center text-sm text-stone">
						{isEditMode ? 'Loading case...' : 'Loading case template...'}
					</p>
				{/if}

				{#if importWarnings.length > 0}
					<div class="rounded-xl border border-line bg-cream/60 px-4 py-3 text-sm text-ink-soft">
						<div class="flex items-start justify-between gap-3">
							<p class="font-semibold text-ink">
								Imported with {importWarnings.length} issue{importWarnings.length === 1 ? '' : 's'} to review
							</p>
							<button
								type="button"
								onclick={() => (importWarnings = [])}
								class="text-xs font-semibold text-stone-soft"
								aria-label="Dismiss"
							>
								&times;
							</button>
						</div>
						<ul class="mt-2 flex flex-col gap-1">
							{#each importWarnings as warning (warning)}
								<li class="text-xs">{warning}</li>
							{/each}
						</ul>
					</div>
				{/if}

				<CaseInfoFields
					bind:caseName
					bind:initialBrief
					bind:commonInformation
					bind:simulationDurationMinutes
					bind:accessCode
					bind:collaboratorAdminIds
					maxSimulationDuration={MAX_SIMULATION_DURATION}
					{allAdmins}
					adminsLoading={adminsQuery.isLoading}
					{effectiveOwnerId}
					{showFieldErrors}
					{revealErrors}
				/>

				<CaseGraphEditor {graph} {showFieldErrors} {revealErrors} />

				{#if displayedError}
					<p class="text-sm font-medium text-brand">{displayedError}</p>
				{/if}
				{#if submitSuccess && !suppressInlineSuccess}
					<p class="text-sm font-medium text-success">{submitSuccess}</p>
				{/if}
				{#if showFieldErrors && hasValidationErrors}
					<p class="text-sm font-medium text-brand">
						Resolve the highlighted fields above before submitting.
					</p>
				{/if}

				<button
					type="submit"
					class="self-start rounded-lg bg-brand px-6 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:brightness-95 disabled:cursor-not-allowed disabled:opacity-60"
				>
					{isSubmitting ? 'Submitting…' : 'Submit'}
				</button>
				</fieldset>
			</form>
		</div>
	</div>
</div>
<DestructiveConfirmDialog
	bind:open={() => pendingImportFile !== null, (isOpen) => { if (!isOpen) pendingImportFile = null }}
	title="Replace everything in this form?"
	description="Import will replace everything currently in this form. This cannot be undone."
	confirmLabel="Import"
	pendingLabel="Importing…"
	onConfirm={confirmImport}
/>
